name: qwen3
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - transformers>=4.51.0
    - torch>=2.6
    - accelerate
    - tokenizers
    - safetensors
    - sentencepiece
    - einops
    - protobuf
    - numpy
    - scipy
    - huggingface_hub
    - modelscope
    - triton